# Generated by Django 4.1.5 on 2023-04-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the book.', max_length=200)),
                ('factory', models.CharField(help_text='Builed factory name', max_length=70)),
                ('expiration_date', models.DateField(verbose_name='Date the item will expire.')),
                ('available_date', models.DateField(verbose_name='Date the item will be available.')),
                ('weight', models.IntegerField(help_text='The weight of the item')),
                ('codeNumber', models.CharField(help_text='The code of the product', max_length=100)),
                ('upcNumber', models.CharField(help_text='The UPC number of the product', max_length=100)),
                ('quantity', models.IntegerField(help_text='The count inside one package')),
                ('size', models.CharField(help_text='The size of item in inches', max_length=200)),
                ('category', models.CharField(help_text='Trend, Bestseller or something', max_length=200)),
                ('description', models.TextField(max_length=100000)),
            ],
        ),
    ]
