# Generated by Django 4.1.5 on 2023-04-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iherbItems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.CharField(default='10000T', max_length=100),
        ),
    ]
